import os
import json
from datetime import date
from dotenv import load_dotenv
from openai import OpenAI
from cve_fetcher import fetch_cve, extract_cve_info

load_dotenv()

client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=os.getenv("OPENROUTER_API_KEY"),
)


def generate_modsec_rule(cve_info):
    """Отправляет данные о CVE в LLM и получает черновик правила ModSecurity."""

    prompt = f"""Ты — эксперт по веб-безопасности и ModSecurity (CRS).

Дана уязвимость:
- ID: {cve_info['id']}
- Описание: {cve_info['description']}
- CVSS: {cve_info['cvss_score']}
- CWE: {cve_info['cwe']}

Задача:
1. Определи, можно ли детектировать эксплуатацию этой уязвимости на уровне WAF (HTTP-трафик).
   Если НЕЛЬЗЯ (supply chain, локальная атака, атака вне HTTP) — так и напиши, объясни почему.
2. Если МОЖНО — предложи черновик правила ModSecurity.
   Требования к правилу:
   - Укажи фазу (phase:1 или phase:2 в зависимости от вектора)
   - Используй SecRule с оператором @rx (регулярка) или @pm (pattern match)
   - Добавь обязательные actions: id, phase, deny, status:403, msg, severity, tag
   - id выбери в диапазоне 9000000-9999999 (кастомные правила)
   - Объясни, что делает каждая часть правила
   - Укажи риск ложных срабатываний (low/medium/high) и почему

Формат ответа — JSON:
{{
  "detectable": true/false,
  "reason": "почему можно или нельзя",
  "rule": "текст правила ModSecurity (если detectable)",
  "explanation": "разбор правила",
  "false_positive_risk": "low/medium/high",
  "false_positive_reason": "почему такой риск"
}}
"""

    response = client.chat.completions.create(
        model="qwen/qwen3.8-27b:free",
        messages=[{"role": "user", "content": prompt}],
        timeout=120,
    )

    return response.choices[0].message.content


def parse_llm_response(raw_response):
    """Извлекает JSON из ответа LLM, убирая возможные markdown-обёртки."""
    cleaned = raw_response.strip()
    if cleaned.startswith("```"):
        cleaned = cleaned.split("```")[1]
        if cleaned.startswith("json"):
            cleaned = cleaned[4:]
    return json.loads(cleaned.strip())


def save_rule(cve_id, parsed, output_dir="rules"):
    """Сохраняет правило в файл в папке rules/."""
    os.makedirs(output_dir, exist_ok=True)

    filename = os.path.join(output_dir, f"{cve_id}.conf")
    today = date.today().isoformat()

    with open(filename, "w", encoding="utf-8") as f:
        f.write(f"# Generated by ModSecurity Generator\n")
        f.write(f"# CVE: {cve_id}\n")
        f.write(f"# Date: {today}\n")
        f.write(f"# Status: DRAFT — requires human review\n")
        f.write(f"# FP risk: {parsed.get('false_positive_risk', 'unknown')}\n")
        f.write(f"# Reason: {parsed.get('false_positive_reason', '')}\n\n")

        if parsed.get("detectable"):
            f.write(parsed["rule"] + "\n\n")
            f.write(f"# Explanation:\n")
            for line in parsed.get("explanation", "").split(". "):
                if line.strip():
                    f.write(f"# {line.strip()}.\n")
        else:
            f.write(f"# NOT DETECTABLE via WAF\n")
            f.write(f"# Reason: {parsed.get('reason', '')}\n")

    return filename


if __name__ == "__main__":
    cve_id = "CVE-2021-44228"

    print(f"→ Загружаю данные о {cve_id}...")
    data = fetch_cve(cve_id)
    info = extract_cve_info(data)

    print(f"→ Генерирую правило через LLM...")
    raw = generate_modsec_rule(info)

    print(f"→ Парсю ответ...")
    parsed = parse_llm_response(raw)

    print(f"→ Сохраняю в файл...")
    filename = save_rule(cve_id, parsed)

    print(f"\nГотово! Правило сохранено в: {filename}")
    print(f"\nDetectable: {parsed.get('detectable')}")
    print(f"FP risk: {parsed.get('false_positive_risk')}")
    print(f"\n{parsed.get('rule', parsed.get('reason'))}")