import os
import json
import argparse
from datetime import date
from dotenv import load_dotenv
from openai import OpenAI
from cve_fetcher import fetch_cve, extract_cve_info

load_dotenv()

client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=os.getenv("OPENROUTER_API_KEY"),
)


def generate_modsec_rule(cve_info):
    """Отправляет данные о CVE в LLM и получает черновик правила ModSecurity."""
    
    syntax_example = """
    Пример корректного правила:
    SecRule ARGS|REQUEST_URI "@rx (?i)(union.*select|select.*from)" \\
        "id:9000001,phase:2,deny,status:403,msg:'SQLi attempt',severity:CRITICAL,tag:'sqli'"

    ВАЖНО: первый аргумент SecRule — имя переменной БЕЗ макроса %{}.
    НЕПРАВИЛЬНО: SecRule %{REQUEST_URI} ...
    ПРАВИЛЬНО:   SecRule REQUEST_URI ...
    """

    prompt = f"""Ты — эксперт по веб-безопасности и ModSecurity (CRS).

Дана уязвимость:
- ID: {cve_info['id']}
- Описание: {cve_info['description']}
- CVSS: {cve_info['cvss_score']}
- CWE: {cve_info['cwe']}

Задача:
1. Определи, можно ли детектировать эксплуатацию этой уязвимости на уровне WAF (HTTP-трафик).
   Если НЕЛЬЗЯ (supply chain, локальная атака, атака вне HTTP) — так и напиши, объясни почему.
2. Если МОЖНО — предложи черновик правила ModSecurity.

{syntax_example}

Требования к правилу:
- Укажи фазу (phase:1 или phase:2 в зависимости от вектора)
- Используй SecRule с оператором @rx (регулярка) или @pm (pattern match)
- Добавь обязательные actions: id, phase, deny, status:403, msg, severity, tag
- id выбери в диапазоне 9000000-9999999 (кастомные правила)
- Объясни, что делает каждая часть правила
- Укажи риск ложных срабатываний (low/medium/high) и почему

Допустимые переменные ModSecurity (используй ТОЛЬКО эти):
REQUEST_URI, REQUEST_LINE, REQUEST_METHOD, REQUEST_HEADERS,
REQUEST_HEADERS:<name>, REQUEST_COOKIES, REQUEST_BODY,
ARGS, ARGS_GET, ARGS_POST, ARGS_NAMES, REQUEST_FILENAME, FILES, FILES_NAMES

ЗАПРЕЩЕНО выдумывать переменные. Если не уверен — используй ARGS.

Формат ответа — JSON:
{{
  "detectable": true/false,
  "reason": "почему можно или нельзя",
  "rule": "текст правила ModSecurity (если detectable)",
  "explanation": "разбор правила",
  "false_positive_risk": "low/medium/high",
  "false_positive_reason": "почему такой риск"
}}
"""

    response = client.chat.completions.create(
        model="qwen/qwen3.8-27b:free",
        messages=[{"role": "user", "content": prompt}],
        timeout=120,
    )

    return response.choices[0].message.content  

def parse_llm_response(raw_response):
    """Извлекает JSON из ответа LLM, убирая возможные markdown-обёртки."""
    cleaned = raw_response.strip()
    if cleaned.startswith("```"):
        cleaned = cleaned.split("```")[1]
        if cleaned.startswith("json"):
            cleaned = cleaned[4:]
    return json.loads(cleaned.strip())


def save_rule(cve_id, parsed, output_dir="rules"):
    """Сохраняет правило в файл в папке rules/."""
    os.makedirs(output_dir, exist_ok=True)

    filename = os.path.join(output_dir, f"{cve_id}.conf")
    today = date.today().isoformat()

    with open(filename, "w", encoding="utf-8") as f:
        f.write(f"# Generated by ModSecurity Generator\n")
        f.write(f"# CVE: {cve_id}\n")
        f.write(f"# Date: {today}\n")
        f.write(f"# Status: DRAFT — requires human review\n")
        f.write(f"# FP risk: {parsed.get('false_positive_risk', 'unknown')}\n")
        f.write(f"# Reason: {parsed.get('false_positive_reason', '')}\n\n")

        if parsed.get("detectable"):
            f.write(parsed["rule"] + "\n\n")
            f.write(f"# Explanation:\n")
            for line in parsed.get("explanation", "").split(". "):
                if line.strip():
                    f.write(f"# {line.strip()}.\n")
        else:
            f.write(f"# NOT DETECTABLE via WAF\n")
            f.write(f"# Reason: {parsed.get('reason', '')}\n")

    return filename


def main():
    parser = argparse.ArgumentParser(
        description="Генератор черновиков правил ModSecurity для CVE."
    )
    parser.add_argument(
        "cve_id",
        help="ID уязвимости, например CVE-2021-44228",
    )
    parser.add_argument(
        "-o", "--output",
        default="rules",
        help="Папка для сохранения правил (по умолчанию: rules)",
    )
    parser.add_argument(
        "--no-save",
        action="store_true",
        help="Не сохранять в файл, только вывести в терминал",
    )
    args = parser.parse_args()

    print(f"Загружаю данные о {args.cve_id}...")
    data = fetch_cve(args.cve_id)
    if data is None:
        print(f"Не удалось получить данные о {args.cve_id}. Проверь ID.")
        return

    info = extract_cve_info(data)
    if info is None:
        print(f"Не удалось извлечь информацию о {args.cve_id}.")
        return

    print(f"Генерирую правило через LLM...")
    raw = generate_modsec_rule(info)

    print(f"Собираю ответ...")
    try:
        parsed = parse_llm_response(raw)
    except json.JSONDecodeError as e:
        print(f"LLM вернула невалидный JSON: {e}")
        print("Сырой ответ:")
        print(raw)
        return

    print(f"\nDetectable: {parsed.get('detectable')}")
    print(f"FP risk: {parsed.get('false_positive_risk')}")
    print(f"\n{parsed.get('rule', parsed.get('reason'))}")

    if not args.no_save:
        print(f"\nСохраняю в файл...")
        filename = save_rule(args.cve_id, parsed, output_dir=args.output)
        print(f"Правило сохранено в: {filename}")


if __name__ == "__main__":
    main()